/**
 * go2rtc process supervisor.
 *
 * go2rtc is the media engine: it speaks DVRIP and RTSP to the camera and
 * re-publishes the H.264 track as WebRTC to the browser without transcoding.
 * Keeping it as a child process (rather than reimplementing RTP/WebRTC) is what
 * gives ~200ms end-to-end latency and lets the same server serve any RTSP
 * camera regardless of vendor.
 */

import { spawn, type ChildProcess } from 'node:child_process';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

export interface Go2rtcOptions {
  binaryPath: string;
  configPath: string;
  apiPort: number;
  rtspPort: number;
  webrtcPort: number;
  /** Extra bind address; defaults to all interfaces. */
  host?: string;
  logLevel?: 'info' | 'debug';
}

export class Go2rtc {
  private child: ChildProcess | null = null;
  private logBuffer: string[] = [];
  private starting: Promise<void> | null = null;

  constructor(private readonly opts: Go2rtcOptions) {}

  get apiBase(): string {
    return `http://127.0.0.1:${this.opts.apiPort}`;
  }

  get running(): boolean {
    return this.child !== null && this.child.exitCode === null;
  }

  /** Render the go2rtc YAML for the given streams. */
  static renderConfig(streams: Record<string, string>, opts: Go2rtcOptions): string {
    const host = opts.host ?? '0.0.0.0';
    const lines = [
      '# Generated by Avlija. Edit src/server/main.ts stream definitions, not this file.',
      'api:',
      `  listen: "0.0.0.0:${opts.apiPort}"`,
      'rtsp:',
      `  listen: "${host}:${opts.rtspPort}"`,
      'webrtc:',
      `  candidates: ["${host}:${opts.webrtcPort}"]`,
      'log:',
      `  level: ${opts.logLevel ?? 'info'}`,
      'streams:',
    ];
    for (const [name, url] of Object.entries(streams)) {
      lines.push(`  ${name}: "${url}"`);
    }
    return `${lines.join('\n')}\n`;
  }

  async start(streams: Record<string, string>): Promise<void> {
    if (this.running) return;
    if (this.starting) return this.starting;
    this.starting = this.doStart(streams).finally(() => {
      this.starting = null;
    });
    return this.starting;
  }

  private async doStart(streams: Record<string, string>): Promise<void> {
    const { binaryPath, configPath, apiPort } = this.opts;
    if (!existsSync(binaryPath)) {
      throw new Error(
        `go2rtc binary not found at ${binaryPath}. ` +
          `Download it with: npm run setup:go2rtc (see README).`,
      );
    }
    const yaml = Go2rtc.renderConfig(streams, this.opts);
    const { writeFile, mkdir } = await import('node:fs/promises');
    await mkdir(resolve(configPath, '..'), { recursive: true });
    await writeFile(configPath, yaml, 'utf8');

    this.child = spawn(binaryPath, ['-config', configPath], { stdio: ['ignore', 'pipe', 'pipe'] });
    this.child.stdout?.on('data', (d: Buffer) => this.log(d.toString()));
    this.child.stderr?.on('data', (d: Buffer) => this.log(d.toString()));
    this.child.on('exit', (code) => {
      this.log(`go2rtc exited with code ${code}\n`);
      this.child = null;
    });

    await this.waitForApi(apiPort, 10_000);
  }

  private log(text: string): void {
    this.logBuffer.push(text);
    if (this.logBuffer.length > 200) this.logBuffer.shift();
  }

  logs(): string {
    return this.logBuffer.join('');
  }

  private async waitForApi(port: number, timeoutMs: number): Promise<void> {
    const deadline = Date.now() + timeoutMs;
    for (;;) {
      try {
        const res = await fetch(`http://127.0.0.1:${port}/api/streams`, {
          signal: AbortSignal.timeout(1500),
        });
        if (res.ok) return;
      } catch {
        // not up yet
      }
      if (Date.now() > deadline) throw new Error('go2rtc did not become ready in time');
      await new Promise((r) => setTimeout(r, 250));
    }
  }

  stop(): void {
    this.child?.kill('SIGTERM');
    this.child = null;
  }
}
